"""Generate a sample governance report artifact (robust, in-process).

Runs the SAME agent logic (identical prompts + tools) as the live A2A/MCP stack,
but in-process -- direct tool calls and LLM calls, no HTTP/SSE -- so it is
deterministic and cannot hang on network-of-services flakiness. The live
distributed path (A2A over HTTP, tools over MCP/SSE) runs in docker-compose /
k8s and the Streamlit UI; this script just captures a clean artifact.

    python scripts/generate_report.py --model FRAUD-XGB-GNN-001
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from reg_agents.agents.fraud_agent import _SYS as FRAUD_SYS  # noqa: E402
from reg_agents.agents.report_agent import _SYS as REPORT_SYS  # noqa: E402
from reg_agents.agents.retriever_agent import _SYS as RETRIEVER_SYS  # noqa: E402
from reg_agents.agents.validation_agent import _SYS as VALIDATION_SYS  # noqa: E402
from reg_agents.common import llm  # noqa: E402
from reg_agents.common.corpus import RegulationRetriever  # noqa: E402
from reg_agents.config import get_settings  # noqa: E402
from reg_agents.mcp_servers.fraud_server import score_transaction  # noqa: E402
from reg_agents.mcp_servers.model_registry_server import (  # noqa: E402
    get_model_documentation,
    get_model_metadata,
)

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "docs", "sample_report.md")

_retriever = RegulationRetriever()


def _search_regulations(query: str, k: int = 5) -> str:
    hits = _retriever.search(query, k)
    return json.dumps(
        [
            {
                "source": h.document.metadata.get("source", ""),
                "heading": h.document.metadata.get("heading", ""),
                "score": round(h.score, 4),
                "text": h.document.text,
            }
            for h in hits
        ],
        indent=2,
    )


def _reason(system: str, user: str, fallback: str, **kw) -> str:
    try:
        return llm.system_user(system, user, **kw)
    except Exception as exc:  # noqa: BLE001
        return f"[LLM unavailable: {exc}]\n\n{fallback}"


def run_review_inprocess(model_id: str, txn: dict) -> dict:
    meta = get_model_metadata(model_id)
    docs = get_model_documentation(model_id)
    val_rules = _search_regulations(
        f"model risk management validation and monitoring requirements for {model_id}", 5
    )
    validation = _reason(
        VALIDATION_SYS,
        f"MODEL METADATA:\n{meta}\n\nMODEL DOCUMENTATION:\n{docs}\n\n"
        f"RELEVANT REGULATIONS:\n{val_rules}",
        fallback=f"Metadata:\n{meta}\n\nRules:\n{val_rules}",
        max_tokens=1400,
    )

    score = score_transaction(**txn)
    fraud = _reason(FRAUD_SYS, f"Fraud model output (JSON):\n{score}",
                    fallback=f"Fraud output:\n{score}")

    reg_ctx_rules = _search_regulations(
        "SR 11-7 model risk management requirements and fair-lending / consumer "
        "protection rules (ECOA, FCRA, UDAAP, Reg E) for validating, explaining, "
        "and monitoring an AI-based card transaction fraud model", 6
    )
    reg_ctx = _reason(
        RETRIEVER_SYS,
        f"Question:\nWhat regulatory requirements apply to validating and "
        f"monitoring an AI-based fraud model?\n\nRegulation excerpts (JSON):\n{reg_ctx_rules}",
        fallback=f"Excerpts:\n{reg_ctx_rules}",
    )

    combined = (
        f"MODEL ID: {model_id}\n\n## Validation Findings\n{validation}\n\n"
        f"## Fraud / Performance Analysis\n{score}\n{fraud}\n\n"
        f"## Regulatory Context\n{reg_ctx}\n"
    )
    report = _reason(REPORT_SYS, f"Source material:\n\n{combined}",
                     fallback=f"# Governance Report\n\n{combined}", max_tokens=1800)
    return {
        "validation": validation,
        "fraud_score": score,
        "fraud": fraud,
        "regulatory_context": reg_ctx,
        "report": report,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="FRAUD-XGB-GNN-001")
    args = ap.parse_args()
    txn = {"amount": 4200.0, "is_foreign": True, "merchant_risk": 0.6,
           "hour": 2, "velocity_24h": 9}

    s = get_settings()
    r = run_review_inprocess(args.model, txn)
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    doc = f"""# Sample Governance Report — {args.model}

> Generated by the `reg-agents` pipeline on {ts}.
> LLM provider: **{s.llm_provider}** (`{s.active_model}`) ·
> Embeddings: **{s.embedding_provider}** · Vector backend: **{s.vector_backend}** ·
> Fraud backend: **{s.triton_url or 'local heuristic'}**
>
> Same agent logic as the live A2A/MCP stack (validation, fraud, retriever,
> report), captured here as a committed artifact. In production these run as
> independent A2A services calling tools over MCP; see docs/ARCHITECTURE.md.

---

## Final Report (Report Agent)

{r['report']}

---

## Appendix A — Validation Agent findings

{r['validation']}

---

## Appendix B — Fraud Agent analysis

Transaction under review: `{txn}`

```json
{r['fraud_score']}
```

{r['fraud']}

---

## Appendix C — Retriever Agent regulatory context

{r['regulatory_context']}
"""
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(doc)
    print(f"wrote {OUT} ({len(doc)} chars)")


if __name__ == "__main__":
    main()
