"""Generate the model-development lifecycle artifacts (robust, in-process).

Runs the SAME logic as the live Developer -> Validator -> Audit A2A agents
(identical prompts + the real scikit-learn bake-off), but in-process so it is
deterministic and cannot hang. Produces four committed artifacts per task under
docs/lifecycle/<task>/:

    00_model_bakeoff_leaderboard.md   (candidate options + champion selection)
    01_model_development_document.md  (1st line — developer)
    02_independent_validation_report.md (2nd line — validator)
    03_internal_audit_report.md       (3rd line — audit)

    python scripts/generate_lifecycle.py --task fraud
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from reg_agents.agents.audit_agent import _SYS as AUDIT_SYS  # noqa: E402
from reg_agents.agents.developer_agent import _SYS as DEV_SYS  # noqa: E402
from reg_agents.agents.validator_agent import _SYS as VAL_SYS  # noqa: E402
from reg_agents.common import llm, modeling  # noqa: E402
from reg_agents.common.corpus import RegulationRetriever  # noqa: E402
from reg_agents.config import get_settings  # noqa: E402

LIFECYCLE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "lifecycle"
)

_retriever = RegulationRetriever()


def _search(query: str, k: int = 6) -> str:
    hits = _retriever.search(query, k)
    return json.dumps(
        [
            {
                "source": h.document.metadata.get("source", ""),
                "heading": h.document.metadata.get("heading", ""),
                "text": h.document.text,
            }
            for h in hits
        ],
        indent=2,
    )


def _reason(system: str, user: str, fallback: str, **kw) -> str:
    try:
        return llm.system_user(system, user, **kw)
    except Exception as exc:  # noqa: BLE001
        return f"[LLM unavailable: {exc}]\n\n{fallback}"


def _leaderboard_table(bakeoff: dict) -> str:
    cols = ["model", "roc_auc", "pr_auc", "ks", "f1", "precision", "recall", "brier"]
    header = "| " + " | ".join(cols) + " |\n"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |\n"
    rows = ""
    champ = bakeoff["champion"]["model"]
    for r in bakeoff["leaderboard"]:
        marker = " ⭐" if r["model"] == champ else ""
        cells = [str(r[c]) for c in cols]
        cells[0] = cells[0] + marker
        rows += "| " + " | ".join(cells) + " |\n"
    return header + sep + rows


def generate(task_id: str) -> str:
    s = get_settings()
    bakeoff = modeling.run_bakeoff(task_id)
    bakeoff_raw = json.dumps(bakeoff, indent=2)
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    task = bakeoff["task"]
    champ = bakeoff["champion"]

    dev_doc = _reason(DEV_SYS, f"MODEL BAKE-OFF RESULT (JSON):\n{bakeoff_raw}",
                      fallback=bakeoff_raw, max_tokens=1600)

    val_rules = _search(
        f"independent model validation, effective challenge, benchmarking, outcomes "
        f"analysis and fair-lending review under SR 11-7 / OCC 2011-12 for a "
        f"{task['name']} model", 6)
    val_report = _reason(
        VAL_SYS,
        f"MODEL DEVELOPMENT DOCUMENT:\n{dev_doc}\n\nCANDIDATE LEADERBOARD (JSON):\n"
        f"{bakeoff_raw}\n\nRELEVANT REGULATIONS:\n{val_rules}",
        fallback=dev_doc, max_tokens=1700)

    audit_rules = _search(
        "model risk management governance, roles and responsibilities, board and "
        "senior management oversight, documentation, internal audit role and "
        "independence under SR 11-7 / OCC 2011-12", 6)
    audit_report = _reason(
        AUDIT_SYS,
        f"MODEL DEVELOPMENT DOCUMENT:\n{dev_doc}\n\nINDEPENDENT VALIDATION REPORT:\n"
        f"{val_report}\n\nGOVERNANCE REGULATIONS:\n{audit_rules}",
        fallback=val_report, max_tokens=1600)

    banner = (
        f"> Generated by the `reg-agents` model-development lifecycle on {ts}.\n"
        f"> LLM: **{s.llm_provider}** (`{s.active_model}`) · "
        f"Bake-off: **scikit-learn** (GPU analog: RAPIDS cuML / XGBoost).\n"
        f"> Task: **{task['name']}** · Champion: **{champ['model']}** "
        f"(ROC-AUC {champ['roc_auc']}, KS {champ['ks']}).\n"
    )

    out_dir = os.path.join(LIFECYCLE_DIR, task_id)
    os.makedirs(out_dir, exist_ok=True)

    files = {
        "00_model_bakeoff_leaderboard.md": (
            f"# Model Bake-off — {task['name']}\n\n{banner}\n"
            f"**Objective:** {task['objective']}\n\n"
            f"**Dataset:** `{bakeoff['dataset']['path']}` — {bakeoff['dataset']['n_rows']} rows "
            f"({bakeoff['dataset']['n_train']} train / {bakeoff['dataset']['n_test']} test), "
            f"positive rate {bakeoff['dataset']['positive_rate']}. "
            f"Features: {', '.join(bakeoff['dataset']['features'])}.\n\n"
            f"**Primary metric:** `{bakeoff['primary_metric']}` (⭐ = selected champion)\n\n"
            f"{_leaderboard_table(bakeoff)}\n"
            f"**Selection rationale:** {bakeoff['selection_rationale']}\n"
        ),
        "01_model_development_document.md": (
            f"# Model Development Document — {task['name']}\n\n"
            f"*First line of defense — Developer Agent*\n\n{banner}\n---\n\n{dev_doc}\n"
        ),
        "02_independent_validation_report.md": (
            f"# Independent Validation Report — {task['name']}\n\n"
            f"*Second line of defense — Validator Agent (effective challenge)*\n\n{banner}\n---\n\n{val_report}\n"
        ),
        "03_internal_audit_report.md": (
            f"# Internal Audit Report — {task['name']}\n\n"
            f"*Third line of defense — Audit Agent (process assurance)*\n\n{banner}\n---\n\n{audit_report}\n"
        ),
    }
    for fname, content in files.items():
        with open(os.path.join(out_dir, fname), "w", encoding="utf-8") as fh:
            fh.write(content)
    return out_dir


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", action="append", default=[])
    ap.add_argument("--all", action="store_true", help="generate for every task")
    args = ap.parse_args()
    tasks = list(modeling.TASKS) if args.all else (args.task or ["fraud"])
    for t in tasks:
        out_dir = generate(t)
        n = len([f for f in os.listdir(out_dir) if f.endswith(".md")])
        print(f"wrote {n} artifacts to {out_dir}")


if __name__ == "__main__":
    main()
